### ISSUE TITLE
Notice - Undefined index: url

### ISSUE THREAD

**Issue by Findus23** [digitalist-se/TrackerDomain#1]
Hi,

Someone on the forum reported this issue with the plugin:

> WARNING: /plugins/TrackerDomain/TrackerDomain.php(106): Notice - Undefined index: url

https://forum.matomo.org/t/warnung-meldung-nach-4-9-0-update/45717?u=lukas

I'm not too familiar with PHP, but I think you can't split the isset() check like this if you are not sure that the index exists:
https://github.com/digitalist-se/TrackerDomain/blob/af25dedafeb742a2358e148ad9254d093b47e9fb/TrackerDomain.php#L106-L107

**Comment by Chardonneaur** [comment]
I am confirming that we are still seeing this error message within the admin panel of Matomo.

**Comment by mikkeschiren** [comment]
Yeah, that was a bit lazy for me to miss this. I will fix this.

**Comment by mikkeschiren** [comment]
A fix for this has been pushed to a new release - 0.2.4.
