### ISSUE TITLE
It's doesn't work with php 8.1 and tag manager

### ISSUE THREAD

**Issue by guytarr** [digitalist-se/TrackerDomain#4]
Hi, I've upgrade php (7.3 -> 8.1) and everything work fine but TrackerDomain in tag manager didn't work :(
i think the problem is in function setTagManagerUrl... I didn't have any errror message in my php log files

![image002](https://user-images.githubusercontent.com/40494615/191061988-e6d73f70-9402-43ee-936a-27ebfdae14fb.png)

**Comment by skitoxe** [comment]
I have the same issue after upgrading. We now run Matomo 4.12.0 and PHP version 8.0.24. And no matter what i enter into the [TrackerDomain] url variable in confing.ini.php i get a blank page in Tagmanager installcode.

**Comment by Starker3** [comment]
I checked and was able to confirm that the tracking code for the Tag Manager does not show up when using PHP 8+
Switching the site to PHP 7.4.30 allows it to show the tracking code again.

**Comment by tomper00** [comment]
Ok confirmed here too, we are looking into it!

**Comment by mikkeschiren** [comment]
This should now be fixed in the latest releases, 0.3.0 and forward.

**Comment by mikkeschiren** [comment]
BTW - sort of happy to see bug reports - as it shows it used - but sorry for the bug itself.

**Comment by skitoxe** [comment]
@mikkeschiren I have now deployed this to our test enviroment and rolled it out to production as well. It works like a charm again! Thanks for your help 😃

**Comment by mikkeschiren** [comment]
Great :) Closing.

**Comment by guytarr** [comment]
> This should now be fixed in the latest releases, 0.3.0 and forward.

Thank you
