### ISSUE TITLE
Is this plugin compatible with Matomo 4.10.x?

### ISSUE THREAD

**Issue by richardkmichael** [digitalist-se/TrackerDomain#5]
I'm new to Matomo and the Developer API.

What code in this plugin requires Matomo 4.11?

I noticed the required Matomo version was previously `4.0.0-b1`, but was bumped to 4.11 in [this commit](https://github.com/digitalist-se/TrackerDomain/commit/83db93fd512772360223dc461c8837ed4a23d583).

However, the Matomo 4.11 [general](https://matomo.org/changelog/matomo-4-11-0/) and [developer](https://developer.matomo.org/changelog) changelogs do not seem to mention anything related to the code in this plugin.

**Comment by mikkeschiren** [comment]
The bump was a mistake, I have fixed that in the latest release, 0.3.1.
